---

- name: "configuration play"
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml


  # "set postgres environment variables"
  environment:
    ENVIRONMENT: production
    TYPEORM_CONNECTION: postgres
    TYPEORM_ENTITIES: ./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST: udapeople-prod.cu1ugcren7gy.us-west-2.rds.amazonaws.com
    TYPEORM_PORT: 5432
    TYPEORM_USERNAME: postgres
    TYPEORM_PASSWORD: udapeople123
    TYPEORM_DATABASE: udapeople-prod

  roles:
    - configure-server
