- name: "BECFG100.01 update"
  become: true
  shell: |
    apt-get -y update

- name: "BECFG100.02 install python3.6"
  become: true
  shell: |
    apt-get -y install python3.6

- name: "BECFG100.03 install nodejs"
  become: true
  shell: |
    apt-get install -y build-essential
    apt-get install -y curl openssl libssl-dev
    curl -sL https://deb.nodesource.com/setup_12.x | bash -
    apt-get install -y nodejs

- name: "BECFG100.04 install pm2"
  become: true
  shell: |
    npm install pm2 -g

- name: "BECFG100.05 check for environment variables"
  become_user: ubuntu
  shell: grep -c "^export TYPEORM_CONNECTION" /etc/environment || true
  register: test_grep

- name: "BECFG100.06 set environment variables"
  become: true
  shell: |
    echo "# environment variables for udapeople" >> /etc/environment
    #echo "export NODE_ENV=production" >> /etc/environment
    #echo "export ENVIRONMENT=production" >> /etc/environment
    echo "export TYPEORM_CONNECTION={{ lookup('env', 'TYPEORM_CONNECTION') }}" >> /etc/environment
    echo "export TYPEORM_ENTITIES=\"./modules/domain/**/*.entity*.{ts,js}"\" >> /etc/environment
    echo "export TYPEORM_HOST={{ lookup('env', 'TYPEORM_HOST') }}" >> /etc/environment
    echo "export TYPEORM_PORT={{ lookup('env', 'TYPEORM_PORT') }}" >> /etc/environment
    echo "export TYPEORM_USERNAME={{ lookup('env', 'TYPEORM_USERNAME') }}" >> /etc/environment
    echo "export TYPEORM_PASSWORD={{ lookup('env', 'TYPEORM_PASSWORD') }}" >> /etc/environment
    echo "export TYPEORM_DATABASE={{ lookup('env', 'TYPEORM_DATABASE') }}" >> /etc/environment
  when: test_grep.stdout == "0"