- name: "BEDPL100.01 make directory"
  become_user: ubuntu
  shell: mkdir -p ~/udapeople/

- name: "BEDPL100.02 deploy backend app"
  become_user: ubuntu
  unarchive:
    src: ../../backend/app.tar.gz
    dest: ~/udapeople/
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: "BEDPL100.03 run backend app"
  become_user: ubuntu
  shell: |
    cd ~/udapeople/
    npm i
    pm2 start main.js --update-env